import Head from "next/head";
import { Inter } from "@next/font/google";
import Layout from "../components/Layout";
import Link from "next/link";
import axios from "axios";
import Header_Table from "../components/HeaderTable";
import OffersTable from "../components/Offers/OffersTable";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const Home = ({ offers }) => {

  const [search, setSearch] = useState("");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout title={"Ofertas"} description="This is the offert page">
          <Header_Table title="Ofertas" />

          <div className="px-2 sm:px-4 py-2.5">
            <div className=" mx-auto bg-white h-full p-5 rounded-lg">
              
              <OffersTable offers={offers} />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
};

export const getServerSideProps = async (context) => {
  const { data: offers } = await axios.get("http://localhost:3000/api/offers/");
  return {
    props: {
      offers,
    },
  };
};

export default Home;
