import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import Layout from '../components/Layout'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })


export const getServerSideProps = async (context) => {
  const { data: clients } = await axios.get(
    "http://localhost:3000/api/clients"
  );
  return {
    props: {
      clients,
    },
  };
};

export default function Home({ clients }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Layout
        title={'Home'}
        description='This is the home page'
      >
        <h1 className='text-5xl font-semibold text-indigo-500 my-5 flex-grow inline-block'>Ofertas
        
        </h1>
        
      </Layout>

      </main>
      
    </>
  )
}
